// <auto-generated />
namespace XrayProWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditBookingsValidationV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditBookingsValidationV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202309150255083_EditBookingsValidationV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
