//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrayProWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public string Id { get; set; }
        public string BookingId { get; set; }
        public string Path { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
